### ISSUE TITLE
Error when selecting plugin on Video Add-On menu

### ISSUE THREAD

**Issue by rissato** [Diblo/KODI-Popcorn-Time#1]
Running on MAC OS X 10.10. Will try on android an update.

11:56:14 T:4583473152  NOTICE: -->Python Interpreter Initialized<--
11:56:18 T:4583473152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: ('invalid syntax', ('/Users/raphaelrissato/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py', 252, 38, '        "udp://open.demonii.com:1337",\n'))
                                            Traceback (most recent call last):
                                              File "/Users/raphaelrissato/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/addon.py", line 3, in <module>
                                                from kodipopcorntime import monkey_patches, plugin
                                              File "/Users/raphaelrissato/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/__init__.py", line 2, in <module>
                                                from kodipopcorntime import common, cmd, library, index
                                              File "/Users/raphaelrissato/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/index.py", line 4, in <module>
                                                from kodipopcorntime.scrapers import yify
                                            SyntaxError: ('invalid syntax', ('/Users/raphaelrissato/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py', 252, 38, '        "udp://open.demonii.com:1337",\n'))
                                            -->End of Python script error report<--
11:56:18 T:140735246426880   ERROR: GetDirectory - Error getting plugin://plugin.video.kodipopcorntime/
11:56:18 T:140735246426880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodipopcorntime/) failed

**Comment by Diblo** [comment]
Hello
Thank you for feedback :)
I have made a new release where the problem is solve.
