### ISSUE TITLE
Movie listings do not show anymore. V1.6.0

### ISSUE THREAD

**Issue by Xer0Point** [Diblo/KODI-Popcorn-Time#102]
The movie listings will not show at all. It attempts to fetch the information and immediately exits. TV and Anime do fine. I have the recorded error logs.

> 13:35:08 1114.014282 T:1714942960   FATAL: [plugin.video.kodipopcorntime] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 37, in <module>
                                                getattr(gui, params.pop('endpoint', 'index'))(params.pop('mediaType', '')).show(**params)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/browse.py", line 45, in show
                                                pages = res['pages']
                                              File "/usr/lib/python2.7/contextlib.py", line 154, in __exit__
                                                self.thing.close()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/media.py", line 28, in close
                                                super(_Base, self).close()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 51, in close
                                                self.raiseAnyError()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 22, in ___run
                                                self._target()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/media.py", line 59, in _run
                                                self._data = self._provider_build_fn(_res, *self._args, **self._kwargs) # 1. Get request parameter. 2. Perform request. 3. Build item.
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/providers/api-fetch.py", line 821, in browse_build
                                                item = _create_item(movie)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/providers/api-fetch.py", line 143, in _create_item
                                                "trailer": trailer
                                            UnboundLocalError: local variable 'trailer' referenced before assignment
13:35:08 1114.206543 T:1956287408   ERROR: GetDirectory - Error getting plugin://plugin.video.kodipopcorntime/?action=trending&categ=movies&endpoint=browse&mediaType=movies&order=-1
13:35:08 1114.207642 T:1956287408   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodipopcorntime/?action=trending&categ=movies&endpoint=browse&mediaType=movies&order=-1) failed

**Comment by fportegies** [comment]
Exact the same issue here!

**Comment by jakub-chatrny** [comment]
Read the project info. This project is not updated. Follow continuing this project by [Markop159](https://github.com/Diblo/KODI-Popcorn-Time/issues/102). Last time I checked everything was working there.

I guess project default API for movies is down (there are different APIs for Movies,TV shows, Anime).

**Comment by luckytig** [comment]
Mine won't even try and fetch info most of the time, can you help?
