### ISSUE TITLE
UTF8 problem in search

### ISSUE THREAD

**Issue by olabri** [Diblo/KODI-Popcorn-Time#4]
If you search for a special char you get the follwing error:

(I searched for Wall-E)

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xb7' in position 4: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/olabri/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 7, in <module>
                                                plugin.run()
                                              File "/home/olabri/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 334
, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/olabri/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 306
, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/olabri/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.p
y", line 229, in yify_search
                                                plugin.redirect(plugin.url_for("yify_search_query", query_term=query, quality="all", page=1, limit=MOVIES_PER_PAGE
))
                                              File "/home/olabri/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 328
, in redirect
                                                return self._dispatch(new_request.path)
                                              File "/home/olabri/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/olabri/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/caching.py", line 51, in _fn
                                                ret = fn(*a, **kwds)
                                              File "/home/olabri/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 179, in _fn
                                                items = list(items)
                                              File "/home/olabri/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/library.py", line 142, in _fn
                                                for item in items:
                                              File "/home/olabri/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py", line 151, in yify_show_data
                                                "path": plugin.url_for("play", uri=create_magnet_url(torrent["hash"], movie["title_long"], torrent["quality"]), sub=suburl),
                                              File "/home/olabri/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py", line 261, in create_magnet_url
                                                return "magnet:?xt=urn:btih:%s&%s" % (torrent_hash, urlencode({'dn' : name, 'tr': trackers}))
                                              File "/usr/lib/python2.7/urllib.py", line 1332, in urlencode
                                                v = quote_plus(str(v))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 4: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by olabri** [comment]
sorry forgot to update repo ot new version...
