### ISSUE TITLE
JSONDecodeError when trying to open any menu

### ISSUE THREAD

**Issue by oblitum** [Diblo/KODI-Popcorn-Time#80]
I'm trying master since beta 2 at my ARM KODI seemed to try caching all the movie before starting, as I've comented at https://github.com/Diblo/KODI-Popcorn-Time/issues/16#issuecomment-148443611.

Still, I've followed the wiki instructions for installation from sources and after installing I'm getting:

```
19:34:50 T:1475343424  NOTICE: -->Python Interpreter Initialized<--
19:34:52 T:1475343424   FATAL: [plugin.video.kodipopcorntime] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 37, in <module>
                                                getattr(gui, params.pop('endpoint', 'index'))(params.pop('mediaType', '')).show(**params)
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/browse.py", line 45, in show
                                                pages = res['pages']
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-imx6.arm-5.95.5/Python-2.7.3/.install_pkg/usr/lib/python2.7/contextlib.py", line 154, in __exit__
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/media.py", line 28, in close
                                                super(_Base, self).close()
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 51, in close
                                                self.raiseAnyError()
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 22, in ___run
                                                self._target()
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/media.py", line 57, in _run
                                                _res = self._handle_param(**self._provider_fn(*self._args, **self._kwargs))
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/media.py", line 25, in _handle_param
                                                return self._request.request_proxy(**param)
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/request.py", line 27, in request_proxy
                                                _data = self.request(proxy, path, params, headers, timeout)
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/request.py", line 56, in request
                                                return self._read(response)
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/request.py", line 128, in _read
                                                data = simplejson.loads(data, 'UTF-8')
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/simplejson/__init__.py", line 522, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/simplejson/decoder.py", line 400, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/simplejson/scanner.py", line 127, in scan_once
                                                return _scan_once(string, idx)
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/simplejson/scanner.py", line 87, in _scan_once
                                                raise JSONDecodeError(errmsg, string, idx)
                                            JSONDecodeError: Expecting value: line 2 column 1 (char 1)
19:34:52 T:1967133232   ERROR: GetDirectory - Error getting plugin://plugin.video.kodipopcorntime/?action=seeds&endpoint=browse&mediaType=movies
19:34:52 T:1967133232   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodipopcorntime/?action=seeds&endpoint=browse&mediaType=movies) failed
```

This happens anytime I click on one of the options for listing movies like "Most Popular" or "Best Rated".

**Comment by oblitum** [comment]
Well, nevermind, just came to know popcorntime gone down anyway.
