### ISSUE TITLE
Getting movies by genre does not work in v0.6.5.

### ISSUE THREAD

**Issue by whoopsie890** [Diblo/KODI-Popcorn-Time#88]
In version 0.6.5 I tried to look up movies by genre and an error pops up. I went through the code and it seems that if you change the url sort parameter from "sort_by" to just "sort" it works. Has this been a problem for anyone else?

**Comment by ofrayechiel** [comment]
Hi,

This has been a problem for me as well, not just getting movies by genre, but by anything (most recent, specific search term, etc.). Installed plugin.video.kodipopcorntime-0.6.5.zip on a raspberry pi 2.

This is the error in the log:



20:08:29 404.832672 T:1752998944  NOTICE: [xbmcswift2] Request for "/search" matches rule for function "search"
20:08:38 413.697418 T:1752998944  NOTICE: [xbmcswift2] Request for "/search/crazy/1" matches rule for function "search_query"
20:08:41 416.631805 T:1752998944  NOTICE: Traceback (most recent call last):
20:08:41 416.632111 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 7, in <module>
20:08:41 416.632233 T:1752998944  NOTICE:     plugin.run()
20:08:41 416.632324 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
20:08:41 416.632446 T:1752998944  NOTICE:     items = self._dispatch(self.request.path)
20:08:41 416.632538 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
20:08:41 416.632629 T:1752998944  NOTICE:     listitems = view_func(**items)
20:08:41 416.632751 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py", line 221, in search
20:08:41 416.632843 T:1752998944  NOTICE:     plugin.redirect(plugin.url_for("search_query", query_term=query, quality="all", page=1, limit=MOVIES_PER_PAGE))
20:08:41 416.632935 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 328, in redirect
20:08:41 416.633148 T:1752998944  NOTICE:     return self._dispatch(new_request.path)
20:08:41 416.633240 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
20:08:41 416.633331 T:1752998944  NOTICE:     listitems = view_func(**items)
20:08:41 416.633423 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/caching.py", line 47, in _fn
20:08:41 416.633545 T:1752998944  NOTICE:     ret = fn(*a, **kwds)
20:08:41 416.633636 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 89, in _fn
20:08:41 416.633728 T:1752998944  NOTICE:     items = list(items)
20:08:41 416.633820 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/library.py", line 121, in _fn
20:08:41 416.633911 T:1752998944  NOTICE:     for item in items:
20:08:41 416.634003 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py", line 100, in show_data
20:08:41 416.634094 T:1752998944  NOTICE:     search_result = url_get_json("%s/api/v2/list_movies.json" % BASE_URL, params=args, headers=HEADERS)
20:08:41 416.634186 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 99, in url_get_json
20:08:41 416.634277 T:1752998944  NOTICE:     data = url_get(*args, **kwargs)
20:08:41 416.634369 T:1752998944  NOTICE:   File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 68, in url_get
20:08:41 416.634460 T:1752998944  NOTICE:     with closing(urllib2.urlopen(req)) as response:
20:08:41 416.634583 T:1752998944  NOTICE:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
20:08:41 416.634674 T:1752998944  NOTICE:     return opener.open(url, data, timeout)
20:08:41 416.634735 T:1752998944  NOTICE:   File "/usr/lib/python2.7/urllib2.py", line 431, in open
20:08:41 416.634857 T:1752998944  NOTICE:     response = self._open(req, data)
20:08:41 416.634949 T:1752998944  NOTICE:   File "/usr/lib/python2.7/urllib2.py", line 449, in _open
20:08:41 416.635071 T:1752998944  NOTICE:     '_open', req)
20:08:41 416.635162 T:1752998944  NOTICE:   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
20:08:41 416.635284 T:1752998944  NOTICE:     result = func(*args)
20:08:41 416.635376 T:1752998944  NOTICE:   File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
20:08:41 416.635498 T:1752998944  NOTICE:     return self.do_open(httplib.HTTPConnection, req)
20:08:41 416.635590 T:1752998944  NOTICE:   File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
20:08:41 416.635681 T:1752998944  NOTICE:     raise URLError(err)
20:08:41 416.635803 T:1752998944  NOTICE: URLError: <urlopen error [Errno -2] Name or service not known>
20:08:41 416.639709 T:1752998944   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno -2] Name or service not known>
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 7, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py", line 221, in search
                                                plugin.redirect(plugin.url_for("search_query", query_term=query, quality="all", page=1, limit=MOVIES_PER_PAGE))
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 328, in redirect
                                                return self._dispatch(new_request.path)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/caching.py", line 47, in _fn
                                                ret = fn(*a, **kwds)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 89, in _fn
                                                items = list(items)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/library.py", line 121, in _fn
                                                for item in items:
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/scrapers/yify.py", line 100, in show_data
                                                search_result = url_get_json("%s/api/v2/list_movies.json" % BASE_URL, params=args, headers=HEADERS)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 99, in url_get_json
                                                data = url_get(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/site-packages/kodipopcorntime/utils.py", line 68, in url_get
                                                with closing(urllib2.urlopen(req)) as response:
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 431, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 449, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno -2] Name or service not known>
                                            -->End of Python script error report<--
20:08:41 416.804291 T:1958486576   ERROR: GetDirectory - Error getting plugin://plugin.video.kodipopcorntime/search
20:08:41 416.806152 T:1958486576   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodipopcorntime/search) failed
