### ISSUE TITLE
Getting movies by genre not working on 0.7.0~alpha2

### ISSUE THREAD

**Issue by ofrayechiel** [Diblo/KODI-Popcorn-Time#90]
On Raspberry Pi 2.

This is the error I get (different from the one I got for the same problem on 0.6.5 - as seen here: https://github.com/Diblo/KODI-Popcorn-Time/issues/88#issuecomment-163707561)

20:31:28 1783.616333 T:1535112224   ERROR: [plugin.video.kodipopcorntime] (Thread-1) (URL) gaierror: [Errno -2] Name or service not known - http://yts.to/api/v2/list_movies.json?order_by=desc&sort_by=seeds&limit=20&genre=Action&quality=all&page=1
20:31:28 1783.630859 T:1535112224  NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (URL) Proxy domain 'http://yts.to' is not working and will therefore have low priority in the future
20:31:29 1783.989990 T:1547691040   FATAL: [plugin.video.kodipopcorntime] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 37, in <module>
                                                getattr(gui, params.pop('endpoint', 'index'))(params.pop('mediaType', '')).show(**params)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/browse.py", line 45, in show
                                                pages = res['pages']
                                              File "/usr/lib/python2.7/contextlib.py", line 154, in __exit__
                                                self.thing.close()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/media.py", line 28, in close
                                                super(_Base, self).close()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 51, in close
                                                self.raiseAnyError()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 22, in ___run
                                                self._target()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/media.py", line 57, in _run
                                                _res = self._handle_param(**self._provider_fn(*self._args, **self._kwargs))
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/media.py", line 25, in _handle_param
                                                return self._request.request_proxy(**param)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/request.py", line 27, in request_proxy
                                                _data = self.request(proxy, path, params, headers, timeout)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/request.py", line 56, in request
                                                return self._read(response)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/request.py", line 128, in _read
                                                data = simplejson.loads(data, 'UTF-8')
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/simplejson/__init__.py", line 522, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/simplejson/decoder.py", line 400, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/simplejson/scanner.py", line 127, in scan_once
                                                return _scan_once(string, idx)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/simplejson/scanner.py", line 87, in _scan_once
                                                raise JSONDecodeError(errmsg, string, idx)
                                            JSONDecodeError: Expecting value: line 2 column 1 (char 1)
20:31:29 1784.177368 T:1958486576   ERROR: GetDirectory - Error getting plugin://plugin.video.kodipopcorntime/?action=genre&endpoint=browse&genre=Action&mediaType=movies
20:31:29 1784.179199 T:1958486576   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodipopcorntime/?action=genre&endpoint=browse&genre=Action&mediaType=movies) failed

**Comment by direk** [comment]
Edit file plugin.video.kodipopcorntime\resources\lib\kodipopcorntime\providers\movies_yify.py
and try to change:
    domains = [
        "http://yts.to",
        "http://eqwww.image.yt"
    ]
to:
    domains = [
        "http://yts.ag",
        "http://eqwww.image.yt"
    ]

**Comment by ofrayechiel** [comment]
Thanks. 
Is there any way to change the domains without having to edit the source code and reinstalling the add-on?
